- name: Assign domain name generated on freemyip.com to the AWS instance
  hosts: all

  vars_prompt:
    - name: freemyip_secret_url
      prompt: https://freemyip.com secret URL
      private: true

  tasks:
    - name: Bind domain name with IPs of current AWS instance
      uri:
        url: "{{ freemyip_secret_url }}{{ item }}"
        return_content: true
      register: freemyip_answer
      failed_when: freemyip_answer.content.strip() != "OK"
      with_items:
        - "" # for IPv4
        - "&myip={{ ansible_facts.default_ipv6.get('address', ansible_facts.default_ipv4.address) }}" # for IPv6 if applicable
